# Generated by Django 4.1.1 on 2022-09-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0009_watchlist_avg_rating_watchlist_number_of_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='watchlist',
            new_name='platform',
        ),
    ]
